name: CI Services

on:
  push:
    paths:
      - "services/**"
      - "workers/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - "package.json"
  pull_request:
    paths:
      - "services/**"
      - "workers/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports: ["6379:6379"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Test services
        run: pnpm --filter services... test -- --runInBand
      - name: Test workers
        run: pnpm --filter workers... test -- --runInBand
