name: CI Web

on:
  push:
    paths:
      - "apps/web/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - "package.json"
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - "turbo.json"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter web lint
      - run: pnpm --filter web test -- --runInBand
      - run: pnpm --filter web build
