name: E2E Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Build web app
        run: pnpm --filter web build
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Run e2e tests
        run: pnpm --filter web test:e2e
